[package]
name = "folder_sync"
version = "1.2.5"
edition = "2021"

[[bin]]
name = "LRGEXSync"
path = "src/main.rs"

[dependencies]
slint = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
winreg = "0.55"
chrono = "0.4"
rfd = "0.15"
ureq = { version = "2", features = ["json"] }
tar = "0.4"
zstd = "0.13"

[profile.release]
lto = true
codegen-units = 1
strip = true

[build-dependencies]
winres = "0.1"
